댓글 생성 기능 구현 #2
softeerbootcamp-3rd/Team3-33ma3 pull request #37
Opened 2024-02-05 09:00 UTC by jbonnie

## 구현 내용
- [ ] 댓글 생성 후 저장
- [ ] 응답에 포함할 게시글 세부사항 클래스, 해당 시점까지의 평균 견적 제시 가격 반환 메소드, 댓글 세부사항 클래스 구현

## 고민 사항
댓글을 생성한 후 함수를 호출하기 때문에 문제가 발생할 가능성은 적지만, 만약 평균 견적 제시 가격을 계산할 때 견적 댓글의 개수가 0일 경우 ArithmeticException을 throw하여 ControllerAdvice상에서 처리하도록 하였다. 

## 기타
댓글 생성 시 글 작성자에게 실시간으로 응답하는 기능은 이후 추가할 예정.

2024-02-05 11:49 UTC, Yang-soeun requested changes

2024-02-05 11:49 UTC, Yang-soeun commented on 33ma3/src/main/java/softeer/be33ma3/service/PostService.java
> +    double priceAvgOfPost(Long postId) {
이 메소드만 public이 안붙어 있어요~!

2024-02-05 11:49 UTC, Yang-soeun commented on 33ma3/src/main/java/softeer/be33ma3/service/PostService.java
> +        IntSummaryStatistics stats = offerList.stream()
이런 방법도 있군요~ LGTM

2024-02-05 11:49 UTC, Yang-soeun commented on 33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
> +        // TODO: 2. 센터 정보 가져오고 작성 가능한지 검증
작성 가능한지 검증한다는게 일반 사용자인지 센터인지 검증한다는 것인가요???

2024-02-05 12:38 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/service/PostService.java
> +    double priceAvgOfPost(Long postId) {
핵심 로직이라고 생각해서 처음에는 private하게 선언하고 싶었는데, 해당 메소드를 OfferService에서 사용하거든요! 그래서 private은 사용을 못했고, 같은 패키지인 service 내 클래스가 사용할 수 있도록 default 접근제어자로 두었습니다! public이 더 나을 것 같으면 코멘트 부탁드려용:)

2024-02-05 12:43 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
> +        // TODO: 2. 센터 정보 가져오고 작성 가능한지 검증
현재 생각하고 있는 검증 사항이 두 가지 있어요!
1. 일반 사용자인지 서비스 센터인지 판단
2. 센터일 경우 해당 게시글에 이미 견적을 작성한 센터인지 판단, 작성했다면 작성 불가하게끔 구현

2024-02-06 04:16 UTC, jbonnie commented
피드백 반영 했어용!

2024-02-06 04:22 UTC, Yang-soeun approved these changes

2024-02-06 04:28 UTC, merged