게시글 작성 기능 구현 #14
softeerbootcamp-3rd/Team3-33ma3 pull request #40
Opened 2024-02-05 14:02 UTC by Yang-soeun

## 구현 내용
- [ ] 게시글 작성 기능 구현
-  작성자의 위치에서 구를 찾아서 매핑하도록 구현
-  게시글과 수리 센터를 매핑하여 저장하도록 구현
- 게시글과 이미지를 매핑하도록 구현
- [ ] 테스트 코드 작성
- 게시글 작성 controller 테스트 코드 작성
- 게시글 작성 service 테스트 코드 작성

## 고민 사항
테스트 코드를 어떻게 하면 잘 작성할 수 있을까....

## 기타
테스트 코드가 너무 지저분한것 같다.. 리팩토링이 필요해보인다

2024-02-05 14:27 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
> +    private int deadline;
long과 int형은 primitive type이라 null 값이 들어올 일이 없는 것 같아요. null을 체크하려면 reference type을 쓰는 건 어때요?!

2024-02-05 14:31 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/repository/RegionRepository.java
> +    Optional<Region> findByRegionName(String region);
테이블 명이 region 이니 필드명과 통일해서 String regionName으로 파라미터를 받는 건 어떨까?! 하고 가볍게 제안해봅니다...^^

2024-02-05 14:43 UTC, jbonnie requested changes
굳굳!! 엄청 다양한 도메인에 대해 유용한 메소드들도 넣어주셨군요~🤟🏼

2024-02-06 03:31 UTC, Yang-soeun commented on 33ma3/src/main/java/softeer/be33ma3/repository/RegionRepository.java
> +    Optional<Region> findByRegionName(String region);
좋아요~~

2024-02-06 03:35 UTC, Yang-soeun commented on 33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
> +    private int deadline;
그러네용 수정하겠습니다~ 감사합니당

2024-02-06 03:41 UTC, Yang-soeun commented
수정했습니다 ~~

2024-02-06 04:17 UTC, jbonnie approved these changes
LGTM~!

2024-02-06 04:22 UTC, merged