게시글 세부사항 조회 기능 #3
softeerbootcamp-3rd/Team3-33ma3 pull request #46
Opened 2024-02-06 06:40 UTC by jbonnie

## 구현 내용
- 경매 완료된 게시글 or 글 작성자의 접근인 경우: 게시글 세부사항 + 해당 게시글에 속해있는 모든 댓글 목록 반환
- 경매 진행중 and 글 작성자가 아닌 유저의 접근인 경우: 게시글 세부사항 + 해당 시점까지의 평균 견적 제시 가격 반환
- 해당 게시글에 견적 제시 댓글을 작성한 유저의 접근인 경우, 추가로 본인이 작성한 댓글 세부사항도 포함하여 반환 

## 고민 사항
어떤 유저냐에 따라 보여지는 화면 구성이 다르다보니 가능한 모든 경우를 고려하기 위해 오래 고민하였음.
프론트 쪽이 반환 데이터의 필드명을 보고 어떤 데이터인지를 쉽게 파악할 수 있도록 반환 객체 필드 네이밍을 고민하였음.

## 기타

2024-02-06 07:00 UTC, Yang-soeun requested changes
LGTM

2024-02-06 07:00 UTC, Yang-soeun commented on 33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
이미지 정보가 누락됐습니다~~

2024-02-06 07:09 UTC, jbonnie commented
이미지 리스트 필드 추가했습니다~!

2024-02-06 08:29 UTC, Yang-soeun approved these changes

2024-02-06 08:30 UTC, merged

2024-02-08 09:06 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
수정했습니다~~