로그인 기능 리팩토링 #56
softeerbootcamp-3rd/Team3-33ma3 pull request #73
Opened 2024-02-10 16:51 UTC by Yang-soeun

## 구현 내용
- [ ] 사용자 타입을 프론트에서 받는 부분을 내부에서 처리하도록 리팩토링 함
- [ ] 일반 사용자는 Member -> Client 라는 이름을 사용하도록 수정
- [ ] findByLoginIdAndPassword(String loginId, String password 사용해서 한번에 가져오도록 수정

## 고민 사항

## 기타

2024-02-11 00:46 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/jwt/CurrentUser.java
> +@Retention(RetentionPolicy.RUNTIME) //리플렉션 등을 활용할 수 있도록 런타임까지 애노테이션 정보가 남아도록 설정
'남아도록' 도 오타 있어요!

2024-02-11 00:51 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
> +        if(memberRepository.findMemberByLoginId(clientSignUpDto.getLoginId()).isPresent()){//아이디가 이미 존재하는 경우
이거 쿼리 메소드 아마 Member 빼고 findByLoginId가 되어야 될 것 같아요!

2024-02-11 00:52 UTC, jbonnie commented on 33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
> +        Member member = Member.createMember(CENTER_TYPE, clientSignUpDto.getLoginId(), clientSignUpDto.getPassword());
CENTER_TYPE -> CLIENT_TYPE인 것 같습니다~~!

2024-02-11 00:54 UTC, jbonnie requested changes
굳 수고하셨어욥!

2024-02-11 12:42 UTC, Yang-soeun commented on 33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
> +        if(memberRepository.findMemberByLoginId(clientSignUpDto.getLoginId()).isPresent()){//아이디가 이미 존재하는 경우
똑같아요!

2024-02-11 13:26 UTC, jbonnie commented
로그인 관련 api 명세서도 업데이트 부탁해용! 프론트 쪽이 기존 걸로 이슈 만든 것 같아요

2024-02-11 13:53 UTC, Yang-soeun commented
넵 배포하고 수정할게용

2024-02-11 14:09 UTC, Yang-soeun commented
오타 수정 다 했습니다 확인해주세용~

2024-02-12 01:39 UTC, jbonnie approved these changes
수고하셨습니다~!!

2024-02-12 05:09 UTC, merged