Modal 세부 기능 구현 #54
softeerbootcamp-3rd/Team3-33ma3 pull request #78
Opened 2024-02-11 16:54 UTC by cmw9957

## 구현 내용
- [ ] 임의 영역 클릭 시 Modal 생성
- [ ] 주소 입력시 지도 위치 이동 및 반경 내 센터를 마커 실시간 표시
- [ ] 반경 입력시 원 도형 표현 및 반경 내 센터를 마커 실시간 표시
- [ ] Modal 닫기 기능

## 고민 사항
Modal에서 표시된 센터에 대한 정보를 정보창을 통해 간단한 정보를 제공하는 기능을 추가해야겠다. 그 다음 '저장' 버튼을 클릭해서 선택한 센터의 정보를 Modal의 상위 컴포넌트로 전달하는 방법을 알아봐야겠다. 그 다음 상수와 함수 분리는 어느정도 기능 구현이 마무리 된 후에 진행하기로 결정했다. 또한, Modal의 렌더 횟수를 최적화하기 위해 isDragend 상태를 제거하니 획기적으로 줄어들었다. 다시 복기할 시간이 있으면 확인해볼 부분이다.

## 기타
너무 힘들었어요. 지홍님,,,,,,,,

2024-02-12 06:05 UTC, chjih requested changes
진짜진짜 고생하셨습니다 민우님 💯

2024-02-12 06:05 UTC, chjih commented on src/components/LocationModal.jsx
>    return createPortal(
createPortal 좋네요 👍

2024-02-12 06:05 UTC, chjih commented on src/components/LocationModal.jsx
> +  });
부모 컴포넌트에서 state를 사용해도 될것 같은데 forwardRef, useImperativeHandle을 사용한 이유가 궁금합니다

2024-02-13 01:06 UTC, cmw9957 commented on src/components/LocationModal.jsx
> +            key={generateKeyBasedOnCurrentTime()}
InputText의 value 값 초기화를 위해 key를 줬습니다

2024-02-13 01:18 UTC, cmw9957 commented on src/components/LocationModal.jsx
> +  });
modal 닫는데 굳이 재렌더링은 필요치 않아서 참조를 사용했고, useImperativeHandle은 부모 컴포넌트에서 자식 컴포넌트의 참조 인스턴스에 접근하기 위해 사용한 훅입니다. 따로 open이라는 함수를 만들어 재사용성도 고려했습니다.

2024-02-13 01:53 UTC, chjih approved these changes

2024-02-13 02:06 UTC, merged